require("user.launch")
require("user.options")
require("user.keymaps")
require("user.autocmds")
require("user.format_on_save")
-- require("user.commands")
-- spec "user.copilot-status"
-- spec "user.diffview"
-- spec "user.illuminate"
-- spec "user.rest"
-- spec("user.gopher")

-- spec("user.noice")
-- spec("user.nvim-dap-go")
spec("user.nvimtree")
spec("user.alpha")
spec("user.animate")
spec("user.autopairs")
spec("user.bigfile")
spec("user.breadcrumbs")
spec("user.cmp")
spec("user.codesnap")
spec("user.colorscheme")
spec("user.comment")
spec("user.copilot")
spec("user.devicons")
spec("user.gen")
spec("user.gh-actions")
spec("user.gitlinker")
spec("user.gitsigns")
spec("user.go")
spec("user.harpoon")
spec("user.indentline")
spec("user.lazygit")
spec("user.lspconfig")
spec("user.lualine")
spec("user.markdown")
spec("user.mason")
spec("user.navic")
spec("user.neogit")
spec("user.none-ls")
spec("user.nvim-dap")
spec("user.obsidian")
spec("user.octo")
spec("user.oil")
spec("user.project")
spec("user.rainbow")
spec("user.schemastore")
spec("user.spectre")
spec("user.telescope")
spec("user.todo")
spec("user.treesitter")
spec("user.trouble")
spec("user.vim-rhubarb")
spec("user.vim-tmux-navigator")
spec("user.whichkey")
spec("user.worktree")
spec("user.zen-mode")
require("user.lazy")
