#!/usr/bin/env sh

# https://www.notion.so/Yabai-8da3b829872d432fac43181b7ff628fc
# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          4
borders active_color=0xff77ff00 inactive_color=0xff494d64 width=8.0 & # brew tap FelixKratz/formulae && brew install borders 
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  2
yabai -m config bottom_padding               2
yabai -m config left_padding                 2
yabai -m config right_padding                2
yabai -m config window_gap                   8

# float these windows with "word" in title
yabai -m rule --add title=" Preferences$" sticky=on layer=above manage=off
yabai -m rule --add title=" Settings$" sticky=on layer=above manage=off

# float these apps
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Keka$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Find My$" sticky=on layer=above manage=off
yabai -m rule --add app="^Okta Verify$" sticky=on layer=above manage=off
yabai -m rule --add app="^Dozer$" sticky=on layer=above manage=off
yabai -m rule --add app="^Stats$" sticky=on layer=above manage=off
yabai -m rule --add app="^1Password$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Settings$" sticky=on layer=above manage=off
yabai -m rule --add app="^Logi Options+$" sticky=on layer=above manage=off
yabai -m rule --add app="^FaceTime$" sticky=on layer=above manage=off
yabai -m rule --add app="^CleanMyMac X$" sticky=on layer=above manage=off
yabai -m rule --add app="^Music$" sticky=on layer=above manage=off
yabai -m rule --add app="^Maps$" sticky=on layer=above manage=off
yabai -m rule --add app="^Raycast$" sticky=on layer=above manage=off

# app borders
# yabai -m rule --add app='.*' border=on
echo "yabai configuration loaded.."
