import = ["~/.sesh.toml"] # Importing local config not in git

[default_session]
startup_command = "nvim -c ':Telescope find_files"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Sesh"
path = "~/repo/dot/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/repo/dot/sesh/.config/sesh/sesh.toml"

[[session]]
name = "Sesh local"
path = "~/.sesh.toml"
startup_command = "nvim ~/.sesh.toml"
preview_command = "bat --color=always ~/.sesh.toml"

[[session]]
name = "Neovim Config"
path = "~/repo/dot/.config/nvim"

[[session]]
name = "dotfiles"
path = "~/repo/dot"
startup_command = "lazygit"

[[session]]
name = "Local Config"
path = "~/.config"
startup_command = "nvim -c ':Oil'"

[[session]]
name = "tmux"
path = "~/repo/dot/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/repo/dot/.config/tmux/tmux.conf"

[[session]]
name = "zsh"
path = "~/repo/dot/.zshrc"

[[session]]
name = "ghostty"
path = "~/repo/dot/.config/ghostty"
startup_command = "nvim config"
preview_command = "bat --color=always ~/repo/dot/.config/ghostty/config"

[[session]]
name = "aws config"
path = "~/.aws"
startup_command = "nvim config"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"
