import = ["~/.sesh.toml"] # Importing local config not in git

[default_session]
startup_command = "nvim"
preview_command = "eza --all --git --icons --color=always {}"

[[window]]
name = "git"
startup_script = "lazygit"


[[session]]
name = "AWS config"
path = "~/.aws"
startup_command = "nvim config"


[[session]]
name = "Aerospace"
path = "~/repo/dot/.config/aerospace"
startup_command = "nvim aerospace.toml"
preview_command = "bat --color=always ~/repo/dot/.config/aerospace/aerospace.toml"


[[session]]
name = "Dotfiles"
path = "~/repo/dot"
# startup_command = "lazygit"
windows = ["git"]


[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Ghostty"
path = "~/repo/dot/.config/ghostty"
startup_command = "nvim config"
preview_command = "bat --color=always ~/repo/dot/.config/ghostty/config"


[[session]]
name = "Lazygit"
path = "~/repo/dot/.config/lazygit"
startup_command = "nvim config.yml"


[[session]]
name = "Local Config"
path = "~/.config"
startup_command = "nvim -c ':Telescope find_files'"


[[session]]
name = "Local Sesh"
path = "~/.sesh.toml"
startup_command = "nvim ~/.sesh.toml"
preview_command = "bat --color=always ~/.sesh.toml"


[[session]]
name = "Local zsh"
path = "~/.env.zsh"
startup_command = "nvim ~/.env.zsh"


[[session]]
name = "Neovim Config"
path = "~/repo/dot/.config/nvim"


[[session]]
name = "SSH Config"
path = "~/.ssh"
startup_command = "nvim config"

[[session]]
name = "Git Config"
path = "~/"
startup_command = "nvim .gitconfig"
preview_command = "bat --color=always ~/.gitconfig"


[[session]]
name = "Sesh"
path = "~/repo/dot/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/repo/dot/sesh/.config/sesh/sesh.toml"


[[session]]
name = "Starship"
path = "~/repo/dot/.config"
startup_command = "nvim starship.toml"
preview_command = "bat --color=always ~/repo/dot/.config/starship.toml"


[[session]]
name = "Tmux"
path = "~/repo/dot/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/repo/dot/.config/tmux/tmux.conf"


[[session]]
name = "Zsh"
path = "~/repo/dot"
startup_command = "nvim .config/zsh/.zshrc"

[[session]]
name = "Gh-dash"
path = "~/repo/dot/.config/gh-dash"
startup_command = "nvim config.yml"
preview_command = "bat --color=always ~/repo/dot/.config/gh-dash/config.yml"
