# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$kubernetes\
$terraform\
$line_break\
$character\
"""
right_format = """$aws$docker_context$golang$helm$lua$nodejs$python$rust$cmd_duration$jobs"""
follow_symlinks = true
command_timeout = 500

[os]
disabled = false
[os.symbols]
Macos = " "

[nodejs]
format = "[$symbol($version)]($style) "

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " 🔒"
truncation_length = 3
truncate_to_repo = false

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
ignore_bare_repo = true
style = "green"

[jobs]
symbol = "+ "
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
disabled = true
symbol = "🐏 "

[rust]
symbol = "🦀 "

[aws]
format = 'on [$symbol$profile:$region]($style) '
style = 'bold blue'
symbol = '🅰 '
[aws.region_aliases]
us-east-1 = 'USE1'
us-east-2 = 'USE2'
us-west-1 = 'USW1'
us-west-2 = 'USW2'
eu-west-1 = 'EUW1'
eu-west-2 = 'EUW2'

[docker_context]
format = 'via [🐋 $context](blue bold)'

[gcloud]
disabled = true
symbol = '🌩️'
format = '[$symbol$project]($style) '
style = 'bold yellow'

[golang]
format = '[🏎💨 $version](bold cyan) '

[helm]
format = '[⎈ $version](bold white) '

[kubernetes]
format = '|[$symbol$context\($namespace\)]($style) '
disabled = false
symbol = "️󱃾 "
style = "blue"
contexts = [
  { context_pattern = "prod" },
  { context_pattern = "staging" },
  { context_pattern = "dev" },
]

[lua]
format = '[🌕 $version](bold blue) '

[python]
format = '[${symbol}(\($virtualenv\))]($style) '
pyenv_version_name = true

[shell]
disabled = true
fish_indicator = ''
powershell_indicator = '_'
unknown_indicator = 'mystery shell'
zsh_indicator = ''
style = 'cyan bold'

[sudo]
disabled = true
style = 'bold green'
symbol = '👨🏽 💻 '

[terraform]
format = '| [$symbol $workspace]($style) '

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = false
show_always = false
